name: 'YAPF Python Code Formatter'
description: 'Run YAPF to format your python code.'
author: "Mr-Rooftop"

branding:
  icon: 'check-circle'
  color: 'green'

runs:
  using: 'docker'
  image: 'Dockerfile'
